/**
 * © 2026 NetLink. All Rights Reserved.
 * Developer: Muhammad Rateb Jabarin
 * Website: aljabareen.com
 * Contact: admin@aljabareen.com | +970597409040
 */
export const dict = {
  en: {
    title: "SAS NET",
    subtitle: "Integrated Smart Enterprise Core",
    nav: { dashboard: "Dashboard", chat: "Operations Room", search: "Knowledge Search", settings: "Settings", files: "File Manager", topology: "Network Topology", security: "Security Radar", analytics: "Analytics & SLA", executive: "Executive AI (CEO)", billing: "Billing & Churn", inventory: "Smart Inventory", crm: "CRM", field: "Field Service", reports: "Report Builder", portal: "Portal Designer", investors: "Investors", suppliers: "Suppliers", boi_expiry: "Smart Subscription Control", management: "Operations & Administration", network_radius: "Network & RADIUS", financial: "Financial Center" },
    roles: {
      super_admin: "Super Administrator",
      admin: "Administrator",
      sas4_manager: "SAS NET Manager (Hadlaq)",
      shareholder: "Shareholder / Investor",
      user: "Standard User"
    },
    auth: {
      login: "Login",
      email: "Email Address",
      username: "Username",
      emailOrUsername: "Email or Username",
      password: "Password",
      forgotPassword: "Forgot Password?",
      signIn: "Sign In",
      welcomeBack: "Welcome Back",
      selectRole: "Select Access Role",
      logout: "Logout",
      rememberMe: "Remember Me",
      loggedInAs: "Logged in as",
      withRole: "with role"
    },
    investor: {
      dashboard: "Investor Dashboard",
      myStocks: "My Stocks",
      transactions: "Transaction History",
      profitLoss: "Profit & Loss Report",
      dividends: "Dividends Report",
      accountInfo: "Account Information",
      totalValue: "Total Portfolio Value",
      availableShares: "Available Shares",
      performance: "Portfolio Performance"
    },
    dashboard: {
      aiRoom: "AI Operations Room", search: "Knowledge Search", dbCount: "Database Files", settings: "Full Control",
      aiStatus: "AI Engine Status", savedConvos: "Saved Conversations", localAi: "Local AI Connectivity", themeToggle: "Theme Toggle",
      ready: "Ready", notReady: "Not Ready", active: "Active", offline: "Offline",
      networkTraffic: "Network Traffic", bandwidth: "Bandwidth Usage", alerts: "System Alerts",
      nodesOnline: "Nodes Online", uptime: "System Uptime",
      viewDetails: "View Details",
      recentActivity: "Recent Activity",
      activity1: "Node Alpha-7 latency spike detected",
      activity2: "Database backup completed successfully",
      activity3: "New firewall rule applied by Manager",
      activity4: "Failed login attempt from unknown IP",
      investorSummary: "Investor Summary",
      marketCap: "Market Cap",
      sharePrice: "Share Price",
      dividendYield: "Div. Yield",
      financialOverview: "Financial Overview",
      revenue: "Monthly Revenue",
      expenses: "Monthly Expenses",
      profit: "Net Profit",
      networkHealth: "Network Health",
      quickActions: "Quick Actions",
      managementStats: "Management Overview",
      totalSubscribers: "Total Subscribers",
      totalSuppliers: "Total Suppliers",
      totalAdmins: "System Admins"
    },
    files: {
      locked: "Manager Access Required",
      unlockMsg: "File System access is restricted to Administrators.",
      goToSettings: "Unlock in Settings",
      sysFiles: "System Database",
      upload: "Upload File",
      saveChanges: "Save Changes",
      download: "Download",
      delete: "Delete",
      path: "Path:",
      confirmSaveTitle: "Confirm Modification",
      confirmSaveMsg: "Are you sure you want to write to this database file? This action is permanent and affects the production database.",
      cancel: "Cancel",
      confirm: "Yes, Write to Disk",
      emptyDir: "Directory is empty.",
      errorLoad: "Failed to load directory.",
      successSave: "File saved successfully.",
      successUpload: "File uploaded successfully.",
      selectFile: "Select a file to view or edit its contents."
    },
    chat: { new: "New Chat", search: "Search History...", placeholder: "Type a command or query...", export: "Export", clear: "Clear",
      assistantName: "SAS NET Assistant", online: "Online",
      welcomeMsg: "Hello. I am the SAS NET Operations Assistant. I can help you diagnose network issues, query the knowledge base, or manage configurations. How can I assist you today?",
      quickActions: ['Run Diagnostic', 'Check Logs', 'Restart Node', 'Analyze Traffic']
    },
    search: { 
      placeholder: "Search knowledge base, incidents, or database (Subscribers, Investors, Suppliers, Managers)...", 
      results: "Search Results", 
      searchBtn: "Search Database",
      globalSearch: "Global Database Lookup",
      noResults: "No records found matching your search.",
      categories: {
        all: "All Records",
        subscribers: "Subscribers",
        investors: "Investors",
        suppliers: "Suppliers",
        team: "Managers/Team"
      },
      table: {
        name: "Name",
        type: "Category",
        status: "Status",
        details: "Details",
        action: "View Profile"
      },
      result1: { title: "Resolution Protocol for Node Alpha Outage", desc: "Standard operating procedure for diagnosing and resolving connectivity drops on Alpha-tier nodes. Includes CLI commands and expected output patterns.", tags: ["SOP", "Network"] },
      result2: { title: "Firewall Configuration Guide v2.4", desc: "Updated guidelines for configuring inbound/outbound rules on edge routers to prevent DDoS attacks.", tags: ["Security", "Config"] },
      result3: { title: "Incident Report: Database Desync", desc: "Post-mortem analysis of the database desynchronization event on 2026-03-15. Root cause and preventative measures.", tags: ["Report", "Database"] }
    },
    management: {
      title: "Operations & Administration Center",
      subtitle: "Manage subscribers, digital services, suppliers, investors, administrative staff, and security groups from one unified workspace.",
      tabs: {
        subscribers: "Subscribers",
        suppliers: "Suppliers",
        shareholders: "Investors",
        directors: "Directors (New)",
        deputies: "Staff & Technicians",
        admins: "Administrators",
        iptv: "Digital Services"
      },
      subscribers: {
        title: "Internet Subscribers",
        add: "Add Subscriber",
        stats: {
          total: "Total Subscribers",
          online: "Connected Now",
          activeOffline: "Active (Offline)",
          expired: "Expired",
          suspended: "Suspended",
          demands: "Financial Demands",
          debts: "Credits/Debts",
          expiresSoon: "Expiring in 3 Days",
          explanations: {
            total: "Total count of all registered subscribers in the system.",
            online: "Subscribers currently active and connected to the network.",
            activeOffline: "Valid accounts with active plans but not currently connected.",
            expired: "Subscribers whose subscription period has reached its end.",
            suspended: "Accounts administratively disabled for technical or financial reasons.",
            demands: "Total outstanding amounts due from subscribers to the provider.",
            debts: "Total remaining credit balances in subscriber accounts.",
            expiresSoon: "Active subscribers whose subscription ends within the next 72 hours."
          }
        },
        table: {
          name: "Full Name",
          plan: "Plan",
          status: "Status",
          expiry: "Expiry Date",
          balance: "Balance"
        },
        statuses: {
          all: "All Statuses",
          active: "Active",
          suspended: "Suspended",
          expired: "Expired"
        }
      },
      investors: {
        title: "Investors List",
        add: "Add Investor",
        table: {
          name: "Full Name",
          shares: "Owned Shares",
          buyPrice: "Buy Price",
          ownership: "Ownership %",
          investment: "Total Investment",
          dividends: "Dividends Paid"
        }
      },
      suppliers: {
        title: "Suppliers List",
        add: "Add Supplier",
        table: {
          name: "Supplier Name",
          category: "Category",
          rating: "Rating",
          lastOrder: "Last Order"
        }
      },
      admins: {
        title: "System Administrators (SAS NET)",
        add: "Add Administrator",
        table: {
          name: "Admin Name",
          role: "Role",
          lastLogin: "Last Login",
          permissions: "Permissions"
        }
      },
      iptv: {
        title: "Digital Services Catalog",
        add: "Add Digital Service",
        table: {
          name: "Service Name",
          phone: "Support Contact",
          host: "Endpoint / Host",
          username: "Service Code",
          password: "Access Key",
          serviceType: "Service Type",
          billingCycle: "Billing Cycle",
          status: "Status",
          expiry: "Offer Expiry Date",
          price: "Price",
          cost: "Cost",
          provider: "Provider / Platform"
        },
        statuses: {
          all: "All Statuses",
          active: "Active",
          suspended: "Suspended",
          expired: "Expired"
        },
        serviceTypes: {
          all: "All Types",
          iptv: "IPTV",
          vpn: "VPN",
          static_ip: "Static IP",
          cloud_storage: "Cloud Storage",
          security: "Security Service",
          other: "Other"
        },
        billingCycles: {
          monthly: "Monthly",
          quarterly: "Quarterly",
          yearly: "Yearly",
          one_time: "One Time"
        }
      },
      edit: "Edit Details",
      save: "Save Changes",
      cancel: "Cancel",
      success: "Changes applied to database successfully."
    },
    settings: {
      title: "Settings & Control",
      subtitle: "Manage enterprise configurations, AI behaviors, and network defaults.",
      categories: {
        profile: "Profile & Preferences",
        network: "Network & Infrastructure",
        ai: "AI & Automation",
        billing: "Billing & Subscriptions",
        investors: "Investor Settings",
        backup: "System Backup",
        team: "Team & Roles",
        security: "Security & Access",
        about: "About System & Updates"
      },
      update: {
        newAvailable: "New Update Available!",
        checking: "Checking for updates...",
        checkNow: "Check For Updates",
        upToDate: "System is up to date",
        updateNow: "Update Now",
        installing: "Installing Update...",
        restartMsg: "System will restart after update.",
        version: "Version",
        buildDate: "Build Date",
        latestVersion: "Latest Available",
        currentNotes: "Current Release Notes",
        availableNotes: "Available Update Notes",
        noNotes: "No release notes available."
      },
      profile: {
        language: "Language",
        theme: "Theme",
        notifications: "Notifications",
        twoFactor: "Two-Factor Authentication (2FA)",
        sessionTimeout: "Session Timeout (Minutes)"
      },
      network: {
        boiVlan: "Default B.O.I VLAN",
        hotspotVlan: "Default Hotspot VLAN",
        snmpPolling: "SNMP Polling Interval (Seconds)",
        autoBackup: "Auto-Backup Configurations"
      },
      ai: {
        autoRemediation: "Auto-Remediation Level",
        autoRemediationDesc: "Allow AI to automatically execute fix scripts without human approval.",
        model: "Primary LLM Model",
        creativity: "AI Creativity / Temperature",
        providers: "AI Providers & API Keys",
        localAi: "Local AI (Ollama/LM Studio)",
        googleGemini: "Google Gemini (Family)",
        openAiGpt: "OpenAI GPT (Family)",
        anthropic: "Anthropic Claude",
        grok: "xAI Grok",
        openRouter: "Open Router (All Models)",
        mistral: "Mistral AI",
        apiKey: "API Key",
        endpoint: "Custom Endpoint",
        status: "Status",
        testConnection: "Test Connection",
        active: "Active",
        inactive: "Inactive"
      },
      billing: {
        currency: "Default Currency",
        taxRate: "Default Tax Rate (%)",
        autoSuspend: "Auto-Suspend Unpaid Accounts",
        suspendDays: "Days Overdue Before Suspension",
        decimalPlaces: "Decimal Places"
      },
      investors: {
        sharePrice: "Market Share Price (ILS)",
        buyPrice: "Purchase Price (Buy)",
        sellPrice: "Selling Price (Sell)",
        totalShares: "Total Shares",
        eps: "Earnings Per Share (EPS)",
        dividendYield: "Dividend Yield (%)",
        lastDividendDate: "Last Dividend Date",
        nextEarningsDate: "Next Earnings Date",
        pricingValuation: "Pricing & Valuation",
        performanceData: "Stock Performance Data",
        keyDates: "Key Dates",
        portalTitle: "Investor Relations Portal",
        portalSubtitle: "Manage shares, dividends, and shareholder relations for NetLink.",
        stockLabel: "NetLink Stock (NLK)",
        overview: "Overview",
        trading: "Stock Trading",
        dividends: "Dividends",
        marketCap: "Market Cap",
        totalSharesLabel: "Total Shares",
        epsLabel: "EPS",
        investorsLabel: "Investors",
        performance: "Stock Performance",
        topShareholders: "Top Shareholders",
        viewAll: "View All Shareholders",
        executeTrade: "Execute Trade",
        buy: "Buy",
        sell: "Sell",
        quantity: "Quantity (Shares)",
        orderType: "Order Type",
        orderTypes: {
          market: "Market Price",
          limit: "Limit Order"
        },
        marketPrice: "Market Price",
        limitOrder: "Limit Order",
        estPrice: "Estimated Price",
        fees: "Fees",
        total: "Total",
        confirmBuy: "Confirm Purchase",
        confirmSell: "Confirm Sale",
        history: "Trade History",
        back: "Back to Overview",
        addShareholder: "Add New Shareholder",
        listTitle: "All Shareholders List",
        shareholder: "Shareholder",
        sharesOwned: "Shares Owned",
        ownership: "Ownership %",
        status: "Status",
        actions: "Actions",
        upcoming: "Upcoming Dividend Distribution",
        perShare: "share",
        exDate: "Ex-Dividend Date",
        paymentSettings: "Payment Settings",
        policy: "Dividend Policy",
        quarterly: "Quarterly Payout",
        growth: "Dividend Growth",
        drip: "DRIP Option",
        profile: "Shareholder Profile",
        personalInfo: "Personal Information",
        investmentDetails: "Investment Details",
        managerActions: "Manager Actions",
        editData: "Edit Data",
        reduceShares: "Reduce Shares",
        addShares: "Add Shares",
        adminNotes: "Admin Notes",
        joinDate: "Join Date",
        totalInvestment: "Total Investment",
        currentValue: "Current Value",
        profitLoss: "Profit/Loss",
        date: "Date",
        type: "Type",
        amount: "Amount",
        price: "Price"
      },
      backup: {
        title: "System Backup & Recovery",
        enabled: "Enable Backup System",
        automatic: "Automatic Backup",
        frequency: "Backup Frequency",
        frequencies: {
          daily: "Daily",
          weekly: "Weekly",
          monthly: "Monthly"
        },
        lastBackup: "Last Successful Backup",
        runNow: "Run Backup Now",
        status: "Backup Status"
      },
      team: {
        addUser: "Add New User",
        role: "Role",
        name: "Name",
        email: "Email",
        username: "Username",
        status: "Status",
        active: "Active",
        inactive: "Inactive",
        editUser: "Edit User Permissions",
        saveUser: "Save User",
        deleteUser: "Delete User",
        permissions: "Permissions & Capabilities",
        categories: {
          dashboard: "Dashboard",
          chat: "Operations Room",
          search: "Knowledge Search",
          management: "SAS NET Management",
          files: "File Manager",
          network: "Network & Infrastructure",
          security: "Security & Access",
          executive: "Executive & AI",
          billing: "Billing & Finance",
          inventory: "Inventory & CRM",
          reports: "Reports & Analytics",
          settings: "System Settings"
        },
        perms: {
          view_dashboard: "View Dashboard",
          manage_widgets: "Manage Widgets",
          access_chat: "Access Operations Room",
          clear_chat: "Clear Chat History",
          export_chat: "Export Conversations",
          perform_search: "Perform Knowledge Search",
          view_subscribers: "View Subscribers",
          manage_subscribers: "Manage Subscribers",
          view_suppliers: "View Suppliers",
          manage_suppliers: "Manage Suppliers",
          view_shareholders: "View Shareholders",
          manage_shareholders: "Manage Shareholders",
          view_directors: "View Directors",
          manage_directors: "Manage Directors",
          view_deputies: "View Deputies",
          manage_deputies: "Manage Deputies",
          view_admins: "View Administrators",
          manage_admins: "Manage Administrators",
          access_files: "Access File Manager",
          upload_files: "Upload Files",
          delete_files: "Delete Files",
          view_topology: "View Network Topology",
          manage_topology: "Manage Topology",
          view_security: "View Security Radar",
          manage_security: "Manage Security Rules",
          access_executive: "Access Executive AI",
          manage_ai: "Manage AI Models",
          view_billing: "View Billing & Churn",
          manage_billing: "Manage Billing & Invoices",
          view_inventory: "View Smart Inventory",
          manage_inventory: "Manage Inventory Items",
          view_crm: "View CRM",
          manage_crm: "Manage Customers",
          view_field_service: "View Field Service",
          manage_field_service: "Manage Field Tasks",
          view_reports: "View Reports",
          create_reports: "Create/Build Reports",
          manage_portal: "Manage Portal Designer",
          view_investors: "View Investor Portal",
          manage_investors: "Manage Investor Settings",
          view_boi: "View BOI Expiry",
          manage_boi: "Manage BOI Subscriptions",
          edit_settings: "Edit System Settings",
          manage_team: "Manage Team & Roles",
          view_audit_logs: "View Audit Logs",
          perform_backup: "Perform System Backup"
        },
        all: "Full Access (Super Admin)"
      },
      security: {
        ipWhitelist: "IP Whitelist (Comma separated)",
        auditLogs: "Audit Log Retention (Days)",
        requireVpn: "Require VPN for Access"
      },
      systemStatus: "System Status", providers: "AI Engine Providers", apiKey: "API Key", save: "Save", test: "Test", clear: "Clear",
      roleMgmt: "Role Management", enterPin: "Enter Manager PIN", switchRole: "Switch Role", currentUser: "Current Role", unlock: "Unlock", revert: "Revert to User",
      dbConn: "Database Connection", vectorStore: "Vector Store", localInf: "Local Inference",
      operational: "Operational", syncing: "Syncing", offlineStatus: "Offline", active: "Active"
    },

    financial: {
      title: "Financial Center",
      subtitle: "Manage central balances, agent commissions, and transaction history.",
      masterBalance: "Master Pool (Super Admin)",
      totalLiquidity: "Total System Liquidity",
      agentBalances: "Active Agent Funds",
      transactions: "Transactions Ledger",
      commissions: "Commission Settings",
      topUp: "Top-Up Balance",
      transfer: "Transfer Funds",
      commissionRate: "Commission Rate",
      profitMargin: "Profit Margin",
      from: "Source",
      to: "Recipient",
      type: "Type",
      amount: "Amount",
      date: "Date",
      status: "Status",
      types: {
        topup_agent: "Agent Top-up",
        topup_sub: "Subscriber Charge",
        commission: "Commission Earned",
        transfer: "Internal Transfer",
        withdraw: "Withdrawal"
      }
    },
    currencies: { ILS: "₪ ILS", USD: "$ USD", JOD: "JD JOD" }
  },
  ar: {
    title: "SAS NET",
    subtitle: "النواة المتكاملة لإدارة المؤسسات الذكية",
    nav: { dashboard: "لوحة القيادة", chat: "غرفة العمليات", search: "البحث المعرفي", settings: "الإعدادات", files: "مدير الملفات", topology: "طوبولوجيا الشبكة", security: "رادار الأمان", analytics: "التحليلات والتقارير", executive: "المساعد التنفيذي (المدير)", billing: "الفوترة والمشتركين", inventory: "المخزون الذكي", crm: "إدارة العملاء", field: "الخدمة الميدانية", reports: "منشئ التقارير", portal: "بوابة الدخول", investors: "المستثمرين", suppliers: "الموردين", boi_expiry: "مركز التحكم الذكي في الاشتراكات", management: "مركز الإدارة والعمليات", network_radius: "إدارة الراديوس والشبكة", financial: "المركز المالي" },
    roles: {
      super_admin: "مدير عام (Super Admin)",
      admin: "مدير نظام (Admin)",
      sas4_manager: "مدير SAS NET (حدلق)",
      shareholder: "مساهم / مستثمر",
      user: "مستخدم عادي"
    },
    auth: {
      login: "تسجيل الدخول",
      email: "البريد الإلكتروني",
      username: "اسم المستخدم",
      emailOrUsername: "البريد الإلكتروني أو اسم المستخدم",
      password: "كلمة المرور",
      forgotPassword: "نسيت كلمة المرور؟",
      signIn: "دخول",
      welcomeBack: "مرحباً بك مجدداً",
      selectRole: "اختر دور الوصول",
      logout: "تسجيل الخروج",
      rememberMe: "تذكرني",
      loggedInAs: "تم تسجيل الدخول باسم",
      withRole: "بصلاحية"
    },
    investor: {
      dashboard: "لوحة تحكم المستثمر",
      myStocks: "أسهمي",
      transactions: "سجل المعاملات",
      profitLoss: "تقرير الربح والخسارة",
      dividends: "تقرير الأرباح",
      accountInfo: "معلومات الحساب",
      totalValue: "إجمالي قيمة المحفظة",
      availableShares: "الأسهم المتاحة",
      performance: "أداء المحفظة"
    },
    dashboard: {
      aiRoom: "غرفة عمليات الذكاء الاصطناعي", search: "البحث المعرفي", dbCount: "ملفات قاعدة البيانات", settings: "تحكم كامل",
      aiStatus: "حالة محرك الذكاء الاصطناعي", savedConvos: "المحادثات المحفوظة", localAi: "اتصال الذكاء الاصطناعي المحلي", themeToggle: "تبديل المظهر",
      ready: "جاهز", notReady: "غير جاهز", active: "نشط", offline: "غير متصل",
      networkTraffic: "حركة مرور الشبكة", bandwidth: "استخدام النطاق الترددي", alerts: "تنبيهات النظام",
      nodesOnline: "العقد المتصلة", uptime: "وقت تشغيل النظام",
      viewDetails: "عرض التفاصيل",
      recentActivity: "النشاط الأخير",
      activity1: "تم اكتشاف ارتفاع في زمن الوصول للعقدة Alpha-7",
      activity2: "اكتمل النسخ الاحتياطي لقاعدة البيانات بنجاح",
      activity3: "تم تطبيق قاعدة جدار حماية جديدة بواسطة المدير",
      activity4: "محاولة تسجيل دخول فاشلة من عنوان IP غير معروف",
      investorSummary: "ملخص المستثمرين",
      marketCap: "القيمة السوقية",
      sharePrice: "سعر السهم",
      dividendYield: "عائد الأرباح",
      financialOverview: "نظرة مالية عامة",
      revenue: "الإيرادات الشهرية",
      expenses: "المصاريف الشهرية",
      profit: "صافي الربح",
      networkHealth: "صحة الشبكة",
      quickActions: "إجراءات سريعة",
      managementStats: "نظرة عامة على الإدارة",
      totalSubscribers: "إجمالي المشتركين",
      totalSuppliers: "إجمالي الموردين",
      totalAdmins: "مديرو النظام"
    },
    files: {
      locked: "مطلوب صلاحية المستويات العليا",
      unlockMsg: "الوصول إلى مدير ملفات النظام وقواعد البيانات مقتصر على المدراء.",
      goToSettings: "إلغاء القفل من الإعدادات",
      sysFiles: "قواعد بيانات النظام",
      upload: "رفع ملف",
      saveChanges: "حفظ التعديلات",
      download: "تنزيل",
      delete: "حذف",
      path: "المسار:",
      confirmSaveTitle: "تأكيد التعديل",
      confirmSaveMsg: "هل أنت متأكد من كتابة هذا الملف إلى قاعدة البيانات؟ هذا الإجراء دائم وسيؤثر على قاعدة البيانات الحية.",
      cancel: "إلغاء",
      confirm: "نعم، احفظ التعديلات",
      emptyDir: "المجلد فارغ.",
      errorLoad: "فشل تحميل المجلد.",
      successSave: "تم حفظ الملف بنجاح.",
      successUpload: "تم رفع الملف بنجاح.",
      selectFile: "حدد ملفاً لعرضه أو تعديل محتواه."
    },
    chat: { new: "محادثة جديدة", search: "البحث في السجل...", placeholder: "اكتب أمراً أو استعلاماً...", export: "تصدير", clear: "مسح",
      assistantName: "مساعد SAS NET", online: "متصل",
      welcomeMsg: "مرحباً. أنا مساعد عمليات SAS NET للذكاء الاصطناعي. يمكنني مساعدتك في تشخيص مشكلات الشبكة، أو الاستعلام عن قاعدة المعرفة، أو إدارة التكوينات. كيف يمكنني مساعدتك اليوم؟",
      quickActions: ['تشغيل التشخيص', 'فحص السجلات', 'إعادة تشغيل العقدة', 'تحليل حركة المرور']
    },
    search: { 
      placeholder: "البحث في قاعدة المعرفة، الحوادث، أو قاعدة البيانات (المشتركين، المستثمرين، الموردين، المديرين)...", 
      results: "نتائج البحث", 
      searchBtn: "بحث في القاعدة",
      globalSearch: "البحث الشامل في قاعدة البيانات",
      noResults: "لم يتم العثور على سجلات تطابق بحثك.",
      categories: {
        all: "الكل",
        subscribers: "المشتركين",
        investors: "المستثمرين",
        suppliers: "الموردين",
        team: "المديرين/الفريق"
      },
      table: {
        name: "الاسم",
        type: "الفئة",
        status: "الحالة",
        details: "التفاصيل",
        action: "عرض الملف"
      },
      result1: { title: "بروتوكول الحل لانقطاع العقدة ألفا", desc: "إجراء التشغيل القياسي لتشخيص وحل انقطاع الاتصال في عقد الطبقة ألفا. يتضمن أوامر CLI وأنماط المخرجات المتوقعة.", tags: ["إجراء قياسي", "شبكة"] },
      result2: { title: "دليل تكوين جدار الحماية الإصدار 2.4", desc: "إرشادات محدثة لتكوين القواعد الواردة/الصادرة على أجهزة التوجيه الطرفية لمنع هجمات حجب الخدمة الموزعة (DDoS).", tags: ["أمان", "تكوين"] },
      result3: { title: "تقرير حادث: عدم تزامن قاعدة البيانات", desc: "تحليل ما بعد الوفاة لحدث عدم تزامن قاعدة البيانات في 15-03-2026. السبب الجذري والتدابير الوقائية.", tags: ["تقرير", "قاعدة بيانات"] }
    },
    management: {
      title: "مركز الإدارة والعمليات",
      subtitle: "مساحة موحدة لإدارة المشتركين والخدمات الرقمية والموردين والمستثمرين والطاقم الإداري والمجموعات الأمنية.",
      tabs: {
        subscribers: "المشتركون",
        suppliers: "الموردون",
        shareholders: "المستثمرون",
        directors: "المدراء (النظام الجديد)",
        deputies: "الموظفون والفنيون",
        admins: "المديرون (نظام SAS NET)",
        iptv: "الخدمات الرقمية"
      },
      subscribers: {
        title: "مشتركو الإنترنت",
        add: "إضافة مشترك",
        stats: {
          total: "إجمالي المشتركين",
          online: "متصل الآن",
          activeOffline: "نشط (غير متصل)",
          expired: "منتهي الصلاحية",
          suspended: "موقوف",
          demands: "المطالبات المالية",
          debts: "الديون المستحقة",
          expiresSoon: "تنتهي خلال 3 أيام",
          explanations: {
            total: "إجمالي عدد المشتركين المسجلين في النظام بالكامل.",
            online: "المشتركون المتصلون بالإنترنت والنشطون حالياً.",
            activeOffline: "مشتركون لديهم اشتراك سارٍ ولكنهم غير متصلين حالياً.",
            expired: "المشتركون الذين انتهت فترة صلاحية اشتراكهم.",
            suspended: "حسابات تم تعطيلها يدوياً من الإدارة لأسباب فنية أو مالية.",
            demands: "إجمالي المبالغ المستحقة للمزود من قبل المشتركين.",
            debts: "إجمالي الأرصدة المتبقية والمستحقة للمشتركين.",
            expiresSoon: "المشتركون النشطون الذين تنتهي صلاحية اشتراكهم خلال الـ 72 ساعة القادمة."
          }
        },
        table: {
          name: "الاسم الكامل",
          plan: "الباقة",
          status: "الحالة",
          expiry: "تاريخ الانتهاء",
          balance: "الرصيد"
        },
        statuses: {
          all: "جميع الحالات",
          active: "نشط",
          suspended: "معلق",
          expired: "منتهي"
        }
      },
      investors: {
        title: "قائمة المستثمرين",
        add: "إضافة مستثمر",
        table: {
          name: "الاسم الكامل",
          shares: "عدد الأسهم المملوكة",
          buyPrice: "سعر الأسهم عند الشراء",
          ownership: "نسبة الملكية",
          investment: "إجمالي الاستثمار",
          dividends: "الأرباح المستلمة"
        }
      },
      suppliers: {
        title: "قائمة الموردين",
        add: "إضافة مورد",
        table: {
          name: "اسم المورد",
          category: "الفئة",
          rating: "التقييم",
          lastOrder: "آخر طلب"
        }
      },
      admins: {
        title: "مديرو النظام (SAS NET)",
        add: "إضافة مدير",
        table: {
          name: "اسم المدير",
          role: "الدور",
          lastLogin: "آخر دخول",
          permissions: "الصلاحيات"
        }
      },
      iptv: {
        title: "كتالوج الخدمات الرقمية",
        add: "إضافة خدمة رقمية",
        table: {
          name: "اسم الخدمة",
          phone: "جهة التواصل",
          host: "الرابط / الـ Host",
          username: "رمز الخدمة",
          password: "مفتاح الوصول",
          serviceType: "نوع الخدمة",
          billingCycle: "دورة الفوترة",
          status: "الحالة",
          expiry: "تاريخ انتهاء العرض",
          price: "سعر البيع",
          cost: "التكلفة",
          provider: "المزود / المنصة"
        },
        statuses: {
          all: "جميع الحالات",
          active: "نشط",
          suspended: "معلق",
          expired: "منتهي"
        },
        serviceTypes: {
          all: "كل الأنواع",
          iptv: "IPTV",
          vpn: "VPN",
          static_ip: "IP ثابت",
          cloud_storage: "تخزين سحابي",
          security: "خدمة أمنية",
          other: "أخرى"
        },
        billingCycles: {
          monthly: "شهري",
          quarterly: "ربع سنوي",
          yearly: "سنوي",
          one_time: "مرة واحدة"
        }
      },
      edit: "تعديل البيانات",
      save: "حفظ التغييرات",
      cancel: "إلغاء",
      success: "تم تطبيق التغييرات على قاعدة البيانات بنجاح."
    },
    settings: {
      title: "الإعدادات والتحكم",
      subtitle: "إدارة تكوينات المؤسسة، سلوكيات الذكاء الاصطناعي، والافتراضيات للشبكة.",
      categories: {
        profile: "الملف الشخصي والتفضيلات",
        network: "الشبكة والبنية التحتية",
        ai: "الذكاء الاصطناعي والأتمتة",
        billing: "الفوترة والاشتراكات",
        investors: "إعدادات المستثمرين",
        backup: "النسخ الاحتياطي للنظام",
        team: "الفريق والأدوار",
        security: "الأمان والوصول",
        about: "حول النظام والتحديثات"
      },
      update: {
        newAvailable: "يوجد تحديث جديد متاح!",
        checking: "جاري التحقق من التحديثات...",
        checkNow: "تحقق من التحديثات",
        upToDate: "النظام محدث بالكامل",
        updateNow: "تحديث الآن",
        installing: "جاري تثبيت التحديث...",
        restartMsg: "سيتم إعادة تشغيل النظام بعد التحديث.",
        version: "الإصدار",
        buildDate: "تاريخ البناء",
        latestVersion: "أحدث إصدار متاح",
        currentNotes: "ملاحظات الإصدار الحالي",
        availableNotes: "ملاحظات التحديث الجديد",
        noNotes: "لا توجد ملاحظات متاحة لهذا الإصدار."
      },
      profile: {
        language: "اللغة",
        theme: "المظهر",
        notifications: "الإشعارات",
        twoFactor: "المصادقة الثنائية (2FA)",
        sessionTimeout: "مهلة الجلسة (بالدقائق)"
      },
      network: {
        boiVlan: "VLAN الافتراضي لـ B.O.I",
        hotspotVlan: "VLAN الافتراضي لـ Hotspot",
        snmpPolling: "فترة استطلاع SNMP (بالثواني)",
        autoBackup: "النسخ الاحتياطي التلقائي للتكوينات"
      },
      ai: {
        autoRemediation: "مستوى الإصلاح التلقائي",
        autoRemediationDesc: "السماح للذكاء الاصطناعي بتنفيذ نصوص الإصلاح تلقائياً دون موافقة بشرية.",
        model: "نموذج LLM الأساسي",
        creativity: "إبداع الذكاء الاصطناعي / درجة الحرارة",
        providers: "مزودي الذكاء الاصطناعي ومفاتيح API",
        localAi: "الذكاء الاصطناعي المحلي (Ollama/LM Studio)",
        googleGemini: "Google Gemini (عائلة)",
        openAiGpt: "OpenAI GPT (عائلة)",
        anthropic: "Anthropic Claude",
        grok: "xAI Grok",
        openRouter: "Open Router (جميع النماذج)",
        mistral: "Mistral AI",
        apiKey: "مفتاح API",
        endpoint: "رابط النهاية (Endpoint)",
        status: "الحالة",
        testConnection: "اختبار الاتصال",
        active: "نشط",
        inactive: "غير نشط"
      },
      billing: {
        currency: "العملة الافتراضية",
        taxRate: "معدل الضريبة الافتراضي (%)",
        autoSuspend: "التعليق التلقائي للحسابات غير المدفوعة",
        suspendDays: "أيام التأخير قبل التعليق",
        decimalPlaces: "الخانات العشرية"
      },
      investors: {
        sharePrice: "سعر السهم في السوق (شيكل)",
        buyPrice: "سعر الشراء",
        sellPrice: "سعر البيع",
        totalShares: "إجمالي الأسهم",
        eps: "عائد السهم (EPS)",
        dividendYield: "عائد الربح (%)",
        lastDividendDate: "تاريخ آخر توزيع أرباح",
        nextEarningsDate: "تاريخ الأرباح القادم",
        pricingValuation: "التسعير والتقييم",
        performanceData: "بيانات أداء السهم",
        keyDates: "التواريخ الهامة",
        portalTitle: "بوابة علاقات المستثمرين",
        portalSubtitle: "إدارة الأسهم والأرباح وعلاقات المساهمين لشركة نت لينك.",
        stockLabel: "سهم نت لينك (NLK)",
        overview: "نظرة عامة",
        trading: "تداول الأسهم",
        dividends: "الأرباح",
        marketCap: "القيمة السوقية",
        totalSharesLabel: "إجمالي الأسهم",
        epsLabel: "عائد السهم",
        investorsLabel: "المستثمرون",
        performance: "أداء السهم",
        topShareholders: "كبار المساهمين",
        viewAll: "عرض جميع المساهمين",
        executeTrade: "تنفيذ تداول",
        buy: "شراء",
        sell: "بيع",
        quantity: "الكمية (أسهم)",
        orderType: "نوع الأمر",
        orderTypes: {
          market: "سعر السوق",
          limit: "أمر محدد"
        },
        marketPrice: "سعر السوق",
        limitOrder: "أمر محدد",
        estPrice: "السعر التقديري",
        fees: "الرسوم",
        total: "الإجمالي",
        confirmBuy: "تأكيد الشراء",
        confirmSell: "تأكيد البيع",
        history: "سجل التداولات",
        back: "العودة للملخص",
        addShareholder: "إضافة مساهم جديد",
        listTitle: "قائمة جميع المساهمين",
        shareholder: "المساهم",
        sharesOwned: "الأسهم المملوكة",
        ownership: "نسبة الملكية",
        status: "الحالة",
        actions: "إجراءات",
        upcoming: "توزيع الأرباح القادم",
        perShare: "سهم",
        exDate: "تاريخ الاستحقاق",
        paymentSettings: "إعدادات الدفع",
        policy: "سياسة توزيع الأرباح",
        quarterly: "توزيع ربع سنوي",
        growth: "نمو الأرباح",
        drip: "خيار إعادة الاستثمار",
        profile: "ملف المساهم",
        personalInfo: "المعلومات الشخصية",
        investmentDetails: "تفاصيل الاستثمار",
        managerActions: "إجراءات المدير",
        editData: "تعديل البيانات",
        reduceShares: "تقليل الأسهم",
        addShares: "إضافة أسهم",
        adminNotes: "ملاحظات إدارية",
        joinDate: "تاريخ الانضمام",
        totalInvestment: "إجمالي الاستثمار",
        currentValue: "القيمة الحالية",
        profitLoss: "الربح/الخسارة",
        date: "التاريخ",
        type: "النوع",
        amount: "الكمية",
        price: "السعر"
      },
      backup: {
        title: "النسخ الاحتياطي واستعادة النظام",
        enabled: "تفعيل نظام النسخ الاحتياطي",
        automatic: "نسخ احتياطي تلقائي",
        frequency: "تكرار النسخ الاحتياطي",
        frequencies: {
          daily: "يومي",
          weekly: "أسبوعي",
          monthly: "شهري"
        },
        lastBackup: "آخر نسخة احتياطية ناجحة",
        runNow: "بدء النسخ الاحتياطي الآن",
        status: "حالة النسخ الاحتياطي"
      },
      team: {
        addUser: "إضافة مستخدم جديد",
        role: "الدور",
        name: "الاسم",
        email: "البريد الإلكتروني",
        username: "اسم المستخدم",
        status: "الحالة",
        active: "نشط",
        inactive: "غير نشط",
        editUser: "تعديل صلاحيات المستخدم",
        saveUser: "حفظ المستخدم",
        deleteUser: "حذف المستخدم",
        permissions: "الصلاحيات والإمكانيات",
        categories: {
          dashboard: "لوحة القيادة",
          chat: "غرفة العمليات",
          search: "البحث المعرفي",
          management: "إدارة SAS NET",
          files: "مدير الملفات",
          network: "الشبكة والبنية التحتية",
          security: "الأمان والوصول",
          executive: "المساعد التنفيذي والذكاء الاصطناعي",
          billing: "الفوترة والمالية",
          inventory: "المخزون وإدارة العملاء",
          reports: "التقارير والتحليلات",
          settings: "إعدادات النظام"
        },
        perms: {
          view_dashboard: "عرض لوحة القيادة",
          manage_widgets: "إدارة الأدوات (Widgets)",
          access_chat: "الوصول لغرفة العمليات",
          clear_chat: "مسح سجل المحادثات",
          export_chat: "تصدير المحادثات",
          perform_search: "إجراء البحث المعرفي",
          view_subscribers: "عرض المشتركين",
          manage_subscribers: "إدارة المشتركين",
          view_suppliers: "عرض الموردين",
          manage_suppliers: "إدارة الموردين",
          view_shareholders: "عرض المساهمين",
          manage_shareholders: "إدارة المساهمين",
          view_directors: "عرض المدراء",
          manage_directors: "إدارة المدراء",
          view_deputies: "عرض النواب",
          manage_deputies: "إدارة النواب",
          view_admins: "عرض المديرين",
          manage_admins: "إدارة المديرين",
          access_files: "الوصول لمدير الملفات",
          upload_files: "رفع الملفات",
          delete_files: "حذف الملفات",
          view_topology: "عرض طوبولوجيا الشبكة",
          manage_topology: "إدارة طوبولوجيا الشبكة",
          view_security: "عرض رادار الأمان",
          manage_security: "إدارة قواعد الأمان",
          access_executive: "الوصول للمساعد التنفيذي",
          manage_ai: "إدارة نماذج الذكاء الاصطناعي",
          view_billing: "عرض الفوترة والاشتراكات",
          manage_billing: "إدارة الفواتير والاشتراكات",
          view_inventory: "عرض المخزون الذكي",
          manage_inventory: "إدارة عناصر المخزون",
          view_crm: "عرض إدارة العملاء (CRM)",
          manage_crm: "إدارة بيانات العملاء",
          view_field_service: "عرض الخدمة الميدانية",
          manage_field_service: "إدارة المهام الميدانية",
          view_reports: "عرض التقارير",
          create_reports: "إنشاء/بناء التقارير",
          manage_portal: "إدارة مصمم البوابة",
          view_investors: "عرض بوابة المستثمرين",
          manage_investors: "إدارة إعدادات المستثمرين",
          view_boi: "عرض اشتراكات BOI",
          manage_boi: "إدارة اشتراكات BOI",
          edit_settings: "تعديل إعدادات النظام",
          manage_team: "إدارة الفريق والأدوار",
          view_audit_logs: "عرض سجلات التدقيق",
          perform_backup: "إجراء نسخ احتياطي للنظام"
        },
        all: "وصول كامل (مدير عام)"
      },
      security: {
        ipWhitelist: "القائمة البيضاء لعناوين IP (مفصولة بفواصل)",
        auditLogs: "الاحتفاظ بسجلات التدقيق (بالأيام)",
        requireVpn: "طلب VPN للوصول"
      },
      systemStatus: "حالة النظام", providers: "مزودي محرك الذكاء الاصطناعي", apiKey: "مفتاح API", save: "حفظ", test: "اختبار", clear: "مسح",
      roleMgmt: "إدارة الأدوار", enterPin: "أدخل رمز المدير", switchRole: "تبديل الدور", currentUser: "الدور الحالي", unlock: "إلغاء القفل", revert: "العودة كمستخدم",
      dbConn: "اتصال قاعدة البيانات", vectorStore: "مخزن المتجهات", localInf: "الاستدلال المحلي",
      operational: "يعمل", syncing: "جاري المزامنة", offlineStatus: "غير متصل", active: "نشط"
    },
    financial: {
      title: "المركز المالي",
      subtitle: "إدارة الأرصدة المركزية، عمولات الوكلاء، وسجل العمليات المالية.",
      masterBalance: "الرصيد المركزي (المدير العام)",
      totalLiquidity: "إجمالي السيولة في النظام",
      agentBalances: "أرصدة الوكلاء النشطة",
      transactions: "سجل العمليات المالية",
      commissions: "إعدادات العمولات",
      topUp: "شحن رصيد",
      transfer: "تحويل أموال",
      commissionRate: "نسبة العمولة",
      profitMargin: "هامش الربح",
      from: "المصدر",
      to: "المستلم",
      type: "النوع",
      amount: "المبلغ",
      date: "التاريخ",
      status: "الحالة",
      types: {
        topup_agent: "شحن وكيل",
        topup_sub: "شحن مشترك",
        commission: "عمولة مكتسبة",
        transfer: "تحويل داخلي",
        withdraw: "سحب رصيد"
      }
    },
    currencies: { ILS: "₪ شيكل", USD: "$ دولار", JOD: "JD دينار" }
  }
};
